import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/db";
import SeverityBadge from "@/components/SeverityBadge";
import WarningActions from "@/components/WarningActions";
import WarningLiveStats from "@/components/WarningLiveStats";

export const dynamic = "force-dynamic";

export default async function WarningDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const warning = await prisma.warning.findUnique({
    where: { id },
    include: { location: true, hazardSignal: true },
  });

  if (!warning) notFound();

  return (
    <div className="flex-1">
      <div className="mx-auto max-w-4xl px-6 py-16 md:px-10 md:py-24">
        <Link href="/warnings" className="text-xs text-ink-faint hover:text-ink-muted">
          ← All warnings
        </Link>

        <div className="mt-6 flex items-center gap-3">
          <SeverityBadge severity={warning.severity} />
          <span className="text-xs font-data uppercase tracking-wide text-ink-faint">
            {warning.hazardSignal.type.replace("_", " ")}
          </span>
        </div>

        <h1 className="mt-5 text-4xl leading-tight">{warning.title}</h1>
        <p className="mt-5 text-xl leading-relaxed text-ink-muted max-w-2xl">{warning.body}</p>

        <div className="mt-8 flex flex-wrap gap-x-10 gap-y-3 text-sm text-ink-faint font-data">
          <span>{warning.location.name}, {warning.location.ward}, {warning.location.country}</span>
          <span>generated by {warning.aiModel}</span>
          <span>{new Date(warning.createdAt).toLocaleString()}</span>
        </div>

        <div className="mt-6 border border-hairline p-5 max-w-2xl">
          <p className="text-xs font-data uppercase tracking-wide text-ink-faint mb-2">
            Source hazard reading
          </p>
          <p className="text-sm text-ink-muted">{warning.hazardSignal.summary}</p>
          <p className="mt-2 text-xs text-ink-faint">
            Source: {warning.hazardSignal.source} · observed {new Date(warning.hazardSignal.observedAt).toLocaleString()}
          </p>
        </div>

        <div className="mt-12">
          <WarningActions
            warningId={warning.id}
            status={warning.status}
            initialTitle={warning.title}
            initialBody={warning.body}
          />
        </div>

        {warning.status === "DISPATCHED" && (
          <div className="mt-14 border-t border-hairline pt-12">
            <p className="text-[11px] font-data uppercase tracking-[0.16em] text-ink-faint mb-6">
              Delivery & comprehension - live
            </p>
            <WarningLiveStats warningId={warning.id} />
          </div>
        )}
      </div>
    </div>
  );
}
